### ISSUE TITLE
Username not showing up properly

### ISSUE THREAD

**Issue by BitForger** [KaminoCoding/FriendNamer#2]
From OP:

> I am confused as to how to enter usernames and nicknames on your mod, friend namer.
>  I put in names as it said to do in the config file but I still couldn't get it to work.
>  Here is an image to how I put in usernames and nicknames. https://gyazo.com/e568d916ad02c7d6ef15d4a9ce7d1fac 
> Is this right or how do I fix it?

**Comment by BitForger** [comment]
It _should_ work just like that. The usernames are case-sensitive and must exactly match a users username. Have you tried using it yet? If it doesn't work make sure to tell me.. I'll open a bug report and I'll see what I can do to fix it. Right now i'm using really simple code to try and do it so its very possible that it doesn't work because of its simplicity.

**Comment by BitForger** [comment]
From OP:

> Tried messing around in the config file, but nothing seems to fix the problem. Here is the cfg https://gyazo.com/8de86006cb35d7e329185104195d2799 and it is the exact same username as seen here https://gyazo.com/3d0db1fd5df59249b3574637b6f1037c Not sure what else to tell you, but I'm using liteloader 1.8 with forge version 11.14.1.1397

**Comment by Skarmm** [comment]
Any other info you need from me?

**Comment by BitForger** [comment]
If you can give me a log that would be great! My only suggestion is update to the new recommended forge while I take some time to play with it and see if it works. 
Have you tried restarting the game after setting the names in the config? That may be the cause of the problem. Try that and tell me what happens. ALSO log the user Who's name you want changed with a message in the chat. I want to see if it is just changing the chat one and not the visible one. A mod list would also be nice.

**Comment by Skarmm** [comment]
Alright here is some logs

With all my mods installed that I use: 
http://pastebin.com/kTGV7gHd
Mods used- (Can give links, but I don't think that is the issue as I have tried it with and without before, also using the version of liteloader I was using before for this)
ArmorHUD
bspkr core
StatusHUD
BetterFoliage
Exotic Birds 
Gammabright
Ingame account switch
Item physic
Hudpixel
Autofish
Nonausea
Optifine (1.8.0 HD D5)
PlayerAPI
SmartCursor
Bombzen API
ToggleSneak
Zyins hud

Without other mods:
http://pastebin.com/iAFfZRMJ 

And then here is with updated forge (1563 (Recommended version for 1.8.0):
http://pastebin.com/pMwkJD2w

Again, here is the screenshot of the config I am using: https://gyazo.com/cb06952cbe7bbba8b97396436bcd0398
Trying to change name AngelWings to Test. I've tried restarting after changing the config in game and outside of game using the cfg file, but neither seem to do anything. 

Here is player and chat message:
https://gyazo.com/5c05bc27e8aecae081125a7b47a217aa

**Comment by BitForger** [comment]
Hmm. This is interesting.. When I try and connect SMP LAN my modded client without the mod is rejecting connections. Perhaps the mod isn't as client-side as I thought. I can't remember how much testing i've done and to what extent. I'll start working on it. If you would like, I can keep you updated with builds and give you my latest to test and see if it works for you.

**Comment by Skarmm** [comment]
Whatever you find a need for I can try to help with testing. Thanks for looking into the issue.

**Comment by BitForger** [comment]
@Skarmm 
Here is the mod. Just unzip this into mods. Let me know if it works for you. This is the latest build I was able to generate. I'm having issues with generating builds right now so I can't push a new full version out yet.
[friendNamer-1.8-1.8-0.2.1.34.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/90424/friendNamer-1.8-1.8-0.2.1.34.jar.zip)

**Comment by Skarmm** [comment]
Seems to be crashing for me. Here's the log http://pastebin.com/6pJvWkTS Tried with my current version of forge, and newest 1.8.0 version, with same result.

**Comment by BitForger** [comment]
Alright.. Looks like it's making two copies in one archive. FML... I'll have to clean out my dev space and start clean

**Comment by BitForger** [comment]
@Skarmm 
Here it is! Finally a build that should work!

[friendnamer-1.8-0.2.1.45.zip](https://github.com/KaminoCoding/FriendNamer/files/92811/friendnamer-1.8-0.2.1.45.zip)

**Comment by Skarmm** [comment]
Ugh sorry, still crashing. http://pastebin.com/2wYum7Uu

EDIT: Used the new forge version and now I'm not crashing. omg this is amazing

**Comment by BitForger** [comment]
Ok yeah. Forgot to mention all the builds will be on 11.14.4.1563+ from now on

**Comment by BitForger** [comment]
Awesome! Glad you like
